export default {
  login: "tausif7851",
  id: 72069907,
  node_id: "MDQ6VXNlcjcyMDY5OTA3",
  avatar_url: "https://avatars0.githubusercontent.com/u/72069907?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/tausif7851",
  html_url: "https://github.com/tausif7851",
  followers_url: "https://api.github.com/users/tausif7851/followers",
  following_url:
    "https://api.github.com/users/tausif7851/following{/other_user}",
  gists_url: "https://api.github.com/users/tausif7851/gists{/gist_id}",
  starred_url: "https://api.github.com/users/tausif7851/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/tausif7851/subscriptions",
  organizations_url: "https://api.github.com/users/tausif7851/orgs",
  repos_url: "https://api.github.com/users/tausif7851/repos",
  events_url: "https://api.github.com/users/tausif7851/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/tausif7851/received_events",
  type: "User",
  site_admin: false,
  name: "Mohamed Tousif",
  company: "Freelancer",
  blog: "www.voker.com",
  location: "Mysore, Karnataka",
  email: null,
  hireable: true,
  bio: "I am a developer 🔥",
  twitter_username: "MdTausif",
  public_repos: 215,
  public_gists: 35,
  followers: 55,
  following: 107,
  created_at: "2020-09-29T08:13:33Z",
  updated_at: "2020-12-09T09:14:50Z",
};
